import type { Lexicon } from '../features'

/**
 * German feature overlay. Gender is the whole reason this file is long: it is a
 * lexical fact per noun, it drives the article *and* the adjective ending in
 * both cases, and there is no rule that gets it right. All 123 pack nouns are
 * curated here; the rest of the pack rides on induction.
 *
 * Irregular verbs are curated too — German present tense has stem changes
 * (essen → isst, sehen → sieht, laufen → läuft) that no ending rule produces.
 */
export const germanLexicon: Lexicon = {
  // "Mir ist kalt", never "ich bin kalt".
  hot: { pos: 'adjective', dativeSensation: true },
  // "Mir ist kalt", never "ich bin kalt".
  cold: { pos: 'adjective', dativeSensation: true },
  hungry: { pos: 'adjective', sensation: 'Hunger' },
  thirsty: { pos: 'adjective', sensation: 'Durst' },
  scared: { pos: 'adjective', sensation: 'Angst' },
  // ---- Pronouns ----
  i: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'nom', accusative: 'mich', dative: 'mir' },
  you: { pos: 'pronoun', person: 2, number: 'sg', pronounCase: 'nom', accusative: 'dich', dative: 'dir' },
  we: { pos: 'pronoun', person: 1, number: 'pl', pronounCase: 'nom', accusative: 'uns', dative: 'uns' },
  he: { pos: 'pronoun', person: 3, number: 'sg', pronounCase: 'nom', accusative: 'ihn', dative: 'ihm' },
  she: { pos: 'pronoun', person: 3, number: 'sg', pronounCase: 'nom', accusative: 'sie', dative: 'ihr' },
  they: { pos: 'pronoun', person: 3, number: 'pl', pronounCase: 'nom', accusative: 'sie', dative: 'ihnen' },
  me: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'acc', dative: 'mir' },
  my: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'poss' },
  your: { pos: 'pronoun', person: 2, number: 'sg', pronounCase: 'poss' },

  // ---- Determiners ----
  a: { pos: 'determiner', determinerKind: 'indefinite' },
  the: { pos: 'determiner', determinerKind: 'definite' },
  this: { pos: 'determiner', determinerKind: 'demonstrative' },
  that: { pos: 'determiner', determinerKind: 'demonstrative' },
  some: { pos: 'determiner', determinerKind: 'quantifier' },
  one: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'sg' },
  two: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  three: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  many: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  little: { pos: 'determiner', determinerKind: 'quantifier' },
  // The pack files this as a determiner; it is an adjective.
  big: { pos: 'adjective' },

  // ---- Verbs (irregular present forms) ----
  want: { pos: 'verb', forms: { '1sg': 'will', '2sg': 'willst', '3sg': 'will', pl: 'wollen', past: 'wollte' } },
  like: { pos: 'verb', forms: { '1sg': 'mag', '2sg': 'magst', '3sg': 'mag', pl: 'mögen', past: 'mochte' } },
  have: { pos: 'verb', forms: { '1sg': 'habe', '2sg': 'hast', '3sg': 'hat', pl: 'haben', past: 'hatte' } },
  see: { pos: 'verb', forms: { '1sg': 'sehe', '2sg': 'siehst', '3sg': 'sieht', pl: 'sehen', past: 'sah' } },
  read: { pos: 'verb', forms: { '1sg': 'lese', '2sg': 'liest', '3sg': 'liest', pl: 'lesen', past: 'las' } },
  eat: { pos: 'verb', forms: { '1sg': 'esse', '2sg': 'isst', '3sg': 'isst', pl: 'essen', past: 'aß' } },
  sit: { pos: 'verb', forms: { '1sg': 'sitze', '2sg': 'sitzt', '3sg': 'sitzt', pl: 'sitzen', past: 'saß' } },
  walk: { pos: 'verb', forms: { '1sg': 'laufe', '2sg': 'läufst', '3sg': 'läuft', pl: 'laufen', past: 'lief' } },
  // helfen governs the dative: "Du hilfst mir", never "mich".
  help: { pos: 'verb', objectCase: 'dative', forms: { '1sg': 'helfe', '2sg': 'hilfst', '3sg': 'hilft', pl: 'helfen', past: 'half' } },
  wash: { pos: 'verb', forms: { '1sg': 'wasche', '2sg': 'wäschst', '3sg': 'wäscht', pl: 'waschen', past: 'wusch' } },
  sleep: { pos: 'verb', forms: { '1sg': 'schlafe', '2sg': 'schläfst', '3sg': 'schläft', pl: 'schlafen', past: 'schlief' } },
  close: { pos: 'verb', forms: { '1sg': 'schließe', '2sg': 'schließt', '3sg': 'schließt', pl: 'schließen', past: 'schloss' } },
  open: { pos: 'verb', forms: { '1sg': 'öffne', '2sg': 'öffnest', '3sg': 'öffnet', pl: 'öffnen', past: 'öffnete' } },
  go: { pos: 'verb', forms: { '1sg': 'gehe', '2sg': 'gehst', '3sg': 'geht', pl: 'gehen', past: 'ging' } },
  come: { pos: 'verb', forms: { '1sg': 'komme', '2sg': 'kommst', '3sg': 'kommt', pl: 'kommen', past: 'kam' } },
  stand: { pos: 'verb', forms: { '1sg': 'stehe', '2sg': 'stehst', '3sg': 'steht', pl: 'stehen', past: 'stand' } },
  drink: { pos: 'verb', forms: { '1sg': 'trinke', '2sg': 'trinkst', '3sg': 'trinkt', pl: 'trinken', past: 'trank' } },
  run: { pos: 'verb', forms: { '1sg': 'renne', '2sg': 'rennst', '3sg': 'rennt', pl: 'rennen', past: 'rannte' } },
  talk: { pos: 'verb', forms: { '1sg': 'rede', '2sg': 'redest', '3sg': 'redet', pl: 'reden', past: 'redete' } },

  // ---- Adjectives needing a distinct attributive stem ----
  tall: { pos: 'adjective', attributive: 'hoh' }, // hoch → das hohe Haus
  favorite: { pos: 'adjective', attributive: 'Lieblings' },

  // ---- Nouns: gender, plural, mass, institutional ----
  // People
  mum: { pos: 'noun', gender: 'feminine', proper: true },
  dad: { pos: 'noun', gender: 'masculine', proper: true },
  teacher: { pos: 'noun', gender: 'masculine', plural: 'Lehrer' },
  friend: { pos: 'noun', gender: 'masculine', plural: 'Freunde' },
  brother: { pos: 'noun', gender: 'masculine', plural: 'Brüder' },
  sister: { pos: 'noun', gender: 'feminine', plural: 'Schwestern' },
  grandma: { pos: 'noun', gender: 'feminine', proper: true },
  grandpa: { pos: 'noun', gender: 'masculine', proper: true },
  helper: { pos: 'noun', gender: 'masculine', plural: 'Helfer' },
  doctor: { pos: 'noun', gender: 'masculine', plural: 'Ärzte' },
  class: { pos: 'noun', gender: 'feminine', plural: 'Klassen' },
  // Drinks
  water: { pos: 'noun', gender: 'neuter', mass: true },
  milk: { pos: 'noun', gender: 'feminine', mass: true },
  juice: { pos: 'noun', gender: 'masculine', mass: true },
  tea: { pos: 'noun', gender: 'masculine', mass: true },
  smoothie: { pos: 'noun', gender: 'masculine', plural: 'Smoothies' },
  lemonade: { pos: 'noun', gender: 'feminine', mass: true },
  'hot-drink': { pos: 'noun', gender: 'neuter', mass: true },
  'cold-drink': { pos: 'noun', gender: 'neuter', mass: true },
  cup: { pos: 'noun', gender: 'masculine', plural: 'Becher' },
  straw: { pos: 'noun', gender: 'masculine', plural: 'Strohhalme' },
  bottle: { pos: 'noun', gender: 'feminine', plural: 'Flaschen' },
  sip: { pos: 'noun', gender: 'masculine', plural: 'Schlucke' },
  // Food
  apple: { pos: 'noun', gender: 'masculine', plural: 'Äpfel' },
  banana: { pos: 'noun', gender: 'feminine', plural: 'Bananen' },
  bread: { pos: 'noun', gender: 'neuter', mass: true },
  toast: { pos: 'noun', gender: 'masculine', mass: true },
  sandwich: { pos: 'noun', gender: 'neuter', plural: 'Sandwiches' },
  rice: { pos: 'noun', gender: 'masculine', mass: true },
  pasta: { pos: 'noun', gender: 'feminine', number: 'pl', mass: true },
  soup: { pos: 'noun', gender: 'feminine', plural: 'Suppen' },
  yogurt: { pos: 'noun', gender: 'masculine', mass: true },
  cheese: { pos: 'noun', gender: 'masculine', mass: true },
  cracker: { pos: 'noun', gender: 'masculine', plural: 'Cracker' },
  carrot: { pos: 'noun', gender: 'feminine', plural: 'Karotten' },
  chips: { pos: 'noun', gender: 'masculine', number: 'pl' },
  cookie: { pos: 'noun', gender: 'masculine', plural: 'Kekse' },
  egg: { pos: 'noun', gender: 'neuter', plural: 'Eier' },
  cereal: { pos: 'noun', gender: 'neuter', mass: true },
  fruit: { pos: 'noun', gender: 'neuter', mass: true },
  snack: { pos: 'noun', gender: 'masculine', plural: 'Snacks' },
  dinner: { pos: 'noun', gender: 'neuter', mass: true },
  lunch: { pos: 'noun', gender: 'neuter', mass: true },
  // Body
  head: { pos: 'noun', gender: 'masculine', plural: 'Köpfe' },
  hand: { pos: 'noun', gender: 'feminine', plural: 'Hände' },
  foot: { pos: 'noun', gender: 'masculine', plural: 'Füße' },
  tummy: { pos: 'noun', gender: 'masculine', plural: 'Bäuche' },
  mouth: { pos: 'noun', gender: 'masculine', plural: 'Münder' },
  ear: { pos: 'noun', gender: 'neuter', plural: 'Ohren' },
  eye: { pos: 'noun', gender: 'neuter', plural: 'Augen' },
  arm: { pos: 'noun', gender: 'masculine', plural: 'Arme' },
  leg: { pos: 'noun', gender: 'neuter', plural: 'Beine' },
  back: { pos: 'noun', gender: 'masculine', plural: 'Rücken' },
  tooth: { pos: 'noun', gender: 'masculine', plural: 'Zähne' },
  hair: { pos: 'noun', gender: 'neuter', number: 'pl', mass: true },
  nose: { pos: 'noun', gender: 'feminine', plural: 'Nasen' },
  skin: { pos: 'noun', gender: 'feminine', mass: true },
  heart: { pos: 'noun', gender: 'neuter', plural: 'Herzen' },
  // Places
  home: { pos: 'noun', gender: 'neuter', proper: true, institutional: true },
  school: { pos: 'noun', gender: 'feminine', plural: 'Schulen', institutional: true },
  classroom: { pos: 'noun', gender: 'neuter', plural: 'Klassenzimmer' },
  bathroom: { pos: 'noun', gender: 'neuter', plural: 'Badezimmer' },
  kitchen: { pos: 'noun', gender: 'feminine', plural: 'Küchen' },
  bedroom: { pos: 'noun', gender: 'neuter', plural: 'Schlafzimmer' },
  garden: { pos: 'noun', gender: 'masculine', plural: 'Gärten' },
  shop: { pos: 'noun', gender: 'masculine', plural: 'Läden' },
  car: { pos: 'noun', gender: 'neuter', plural: 'Autos' },
  bus: { pos: 'noun', gender: 'masculine', plural: 'Busse' },
  park: { pos: 'noun', gender: 'masculine', plural: 'Parks' },
  playground: { pos: 'noun', gender: 'masculine', plural: 'Spielplätze' },
  library: { pos: 'noun', gender: 'feminine', plural: 'Büchereien' },
  pool: { pos: 'noun', gender: 'neuter', plural: 'Schwimmbäder' },
  // Home objects
  table: { pos: 'noun', gender: 'masculine', plural: 'Tische' },
  chair: { pos: 'noun', gender: 'masculine', plural: 'Stühle' },
  sofa: { pos: 'noun', gender: 'neuter', plural: 'Sofas' },
  bed: { pos: 'noun', gender: 'neuter', plural: 'Betten', institutional: true },
  door: { pos: 'noun', gender: 'feminine', plural: 'Türen' },
  window: { pos: 'noun', gender: 'neuter', plural: 'Fenster' },
  // School and things
  book: { pos: 'noun', gender: 'neuter', plural: 'Bücher' },
  pencil: { pos: 'noun', gender: 'masculine', plural: 'Stifte' },
  paper: { pos: 'noun', gender: 'neuter', mass: true },
  bag: { pos: 'noun', gender: 'feminine', plural: 'Taschen' },
  coat: { pos: 'noun', gender: 'feminine', plural: 'Jacken' },
  shoes: { pos: 'noun', gender: 'masculine', number: 'pl' },
  lunchbox: { pos: 'noun', gender: 'feminine', plural: 'Brotdosen' },
  tablet: { pos: 'noun', gender: 'neuter', plural: 'Tablets' },
  screen: { pos: 'noun', gender: 'masculine', plural: 'Bildschirme' },
  timer: { pos: 'noun', gender: 'masculine', plural: 'Timer' },
  schedule: { pos: 'noun', gender: 'masculine', plural: 'Stundenpläne' },
  picture: { pos: 'noun', gender: 'neuter', plural: 'Bilder' },
  card: { pos: 'noun', gender: 'feminine', plural: 'Karten' },
  story: { pos: 'noun', gender: 'feminine', plural: 'Geschichten' },
  music: { pos: 'noun', gender: 'feminine', mass: true },
  // Toys
  ball: { pos: 'noun', gender: 'masculine', plural: 'Bälle' },
  blocks: { pos: 'noun', gender: 'masculine', number: 'pl' },
  doll: { pos: 'noun', gender: 'feminine', plural: 'Puppen' },
  'car-toy': { pos: 'noun', gender: 'neuter', plural: 'Spielzeugautos' },
  train: { pos: 'noun', gender: 'feminine', plural: 'Eisenbahnen' },
  puzzle: { pos: 'noun', gender: 'neuter', plural: 'Puzzles' },
  game: { pos: 'noun', gender: 'neuter', plural: 'Spiele' },
  paint: { pos: 'noun', gender: 'feminine', mass: true },
  clay: { pos: 'noun', gender: 'feminine', mass: true },
  bubbles: { pos: 'noun', gender: 'feminine', number: 'pl' },
  swing: { pos: 'noun', gender: 'feminine', plural: 'Schaukeln' },
  slide: { pos: 'noun', gender: 'feminine', plural: 'Rutschen' },
  bike: { pos: 'noun', gender: 'neuter', plural: 'Fahrräder' },
  teddy: { pos: 'noun', gender: 'masculine', plural: 'Teddys' },
  lego: { pos: 'noun', gender: 'neuter', mass: true },
  // Needs
  break: { pos: 'noun', gender: 'feminine', plural: 'Pausen' },
  'quiet-time': { pos: 'noun', gender: 'feminine', mass: true },
  hug: { pos: 'noun', gender: 'feminine', plural: 'Umarmungen' },
  space: { pos: 'noun', gender: 'masculine', mass: true },
  toilet: { pos: 'noun', gender: 'feminine', plural: 'Toiletten', institutional: true },
  medicine: { pos: 'noun', gender: 'feminine', mass: true },
  light: { pos: 'noun', gender: 'neuter', mass: true },
  'dark-2': { pos: 'noun', gender: 'feminine', mass: true },
  noise: { pos: 'noun', gender: 'masculine', mass: true },
  headphones: { pos: 'noun', gender: 'masculine', number: 'pl' },
  blanket: { pos: 'noun', gender: 'feminine', plural: 'Decken' },
  charger: { pos: 'noun', gender: 'neuter', plural: 'Ladegeräte' },
  choice: { pos: 'noun', gender: 'feminine', plural: 'Auswahlen' },
  turn: { pos: 'noun', gender: 'feminine', mass: true },
  'help-please': { pos: 'noun', gender: 'feminine', mass: true },

  /** Not in the pack yet — Talk has no negation tile. */
  not: { pos: 'negation' },
}
