import type { Lexicon } from '../features'

/** Italian overlay: irregular verbs, reflexives, mass nouns, gender exceptions. */
export const italianLexicon: Lexicon = {
  // "All" agrees and takes the definite article after it.
  all: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl', withDefinite: true, feminine: 'tutte' },

  hungry: { pos: 'adjective', sensation: 'fame' },
  thirsty: { pos: 'adjective', sensation: 'sete' },
  cold: { pos: 'adjective', sensation: 'freddo' },
  hot: { pos: 'adjective', sensation: 'caldo' },
  scared: { pos: 'adjective', sensation: 'paura' },
  i: { pos: 'pronoun', person: 1, number: 'sg', accusative: 'mi' },
  you: { pos: 'pronoun', person: 2, number: 'sg', accusative: 'ti' },
  we: { pos: 'pronoun', person: 1, number: 'pl', accusative: 'ci' },
  he: { pos: 'pronoun', person: 3, number: 'sg', accusative: 'lo' },
  she: { pos: 'pronoun', person: 3, number: 'sg', accusative: 'la' },
  they: { pos: 'pronoun', person: 3, number: 'pl', accusative: 'li' },
  me: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'acc', accusative: 'mi' },
  my: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'poss', feminine: 'mia' },
  your: { pos: 'pronoun', person: 2, number: 'sg', pronounCase: 'poss', feminine: 'tua' },

  a: { pos: 'determiner', determinerKind: 'indefinite' },
  the: { pos: 'determiner', determinerKind: 'definite' },
  this: { pos: 'determiner', determinerKind: 'demonstrative' },
  that: { pos: 'determiner', determinerKind: 'demonstrative' },
  some: { pos: 'determiner', determinerKind: 'quantifier' },
  one: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'sg' },
  two: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  three: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  many: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  little: { pos: 'determiner', determinerKind: 'quantifier' },
  big: { pos: 'adjective' },

  // The verbs added in the core rebalance. The -isc- verbs and the stem-changers
  // need stating; the rest follow the rule.
  get: { pos: 'verb', forms: { '1sg': 'ottengo', '2sg': 'ottieni', '3sg': 'ottiene', pl: 'otteniamo', '3pl': 'ottengono' } },
  know: { pos: 'verb', forms: { '1sg': 'so', '2sg': 'sai', '3sg': 'sa', pl: 'sappiamo', '3pl': 'sanno' } },
  finish: { pos: 'verb', forms: { '1sg': 'finisco', '2sg': 'finisci', '3sg': 'finisce', pl: 'finiamo', '3pl': 'finiscono' } },
  hold: { pos: 'verb', forms: { '1sg': 'tengo', '2sg': 'tieni', '3sg': 'tiene', pl: 'teniamo', '3pl': 'tengono' } },
  build: { pos: 'verb', forms: { '1sg': 'costruisco', '2sg': 'costruisci', '3sg': 'costruisce', pl: 'costruiamo', '3pl': 'costruiscono' } },
  give: { pos: 'verb', forms: { '1sg': 'do', '2sg': 'dai', '3sg': 'dà', pl: 'diamo', '3pl': 'danno' } },
  ride: { pos: 'verb', forms: { '1sg': 'vado in bici', '2sg': 'vai in bici', '3sg': 'va in bici', pl: 'andiamo in bici', '3pl': 'vanno in bici' } },
  wake: { pos: 'verb', forms: { '1sg': 'mi sveglio', '2sg': 'ti svegli', '3sg': 'si sveglia', pl: 'ci svegliamo', '3pl': 'si svegliano' } },
  climb: { pos: 'verb', forms: { '1sg': 'mi arrampico', '2sg': 'ti arrampichi', '3sg': 'si arrampica', pl: 'ci arrampichiamo', '3pl': 'si arrampicano' } },
  want: { pos: 'verb', forms: { '1sg': 'voglio', '2sg': 'vuoi', '3sg': 'vuole', '1pl': 'vogliamo', '3pl': 'vogliono', past: 'volevo' } },
  like: { pos: 'verb', experiencerDative: true, forms: { '3sg': 'piace', '3pl': 'piacciono', past: 'piaceva' } },
  need: { pos: 'verb', forms: { '1sg': 'ho bisogno', '2sg': 'hai bisogno', '3sg': 'ha bisogno', '1pl': 'abbiamo bisogno', '3pl': 'hanno bisogno' } },
  have: { pos: 'verb', forms: { '1sg': 'ho', '2sg': 'hai', '3sg': 'ha', '1pl': 'abbiamo', '3pl': 'hanno' } },
  go: { pos: 'verb', forms: { '1sg': 'vado', '2sg': 'vai', '3sg': 'va', '1pl': 'andiamo', '3pl': 'vanno' } },
  come: { pos: 'verb', forms: { '1sg': 'vengo', '2sg': 'vieni', '3sg': 'viene', '1pl': 'veniamo', '3pl': 'vengono' } },
  drink: { pos: 'verb', forms: { '1sg': 'bevo', '2sg': 'bevi', '3sg': 'beve', '1pl': 'beviamo', '3pl': 'bevono' } },
  choose: { pos: 'verb', forms: { '1sg': 'scelgo', '2sg': 'scegli', '3sg': 'sceglie', '1pl': 'scegliamo', '3pl': 'scelgono' } },
  feel: { pos: 'verb', forms: { '1sg': 'mi sento', '2sg': 'ti senti', '3sg': 'si sente', '1pl': 'ci sentiamo', '3pl': 'si sentono' } },
  sit: { pos: 'verb', forms: { '1sg': 'mi siedo', '2sg': 'ti siedi', '3sg': 'si siede', '1pl': 'ci sediamo', '3pl': 'si siedono' } },
  stand: { pos: 'verb', forms: { '1sg': 'sto in piedi', '2sg': 'stai in piedi', '3sg': 'sta in piedi', '1pl': 'stiamo in piedi', '3pl': 'stanno in piedi' } },
  stop: { pos: 'verb', forms: { '1sg': 'mi fermo', '2sg': 'ti fermi', '3sg': 'si ferma', '1pl': 'ci fermiamo', '3pl': 'si fermano' } },

  water: { pos: 'noun', gender: 'feminine', mass: true },
  milk: { pos: 'noun', gender: 'masculine', mass: true },
  juice: { pos: 'noun', gender: 'masculine', mass: true },
  tea: { pos: 'noun', gender: 'masculine', mass: true },
  bread: { pos: 'noun', gender: 'masculine', mass: true },
  rice: { pos: 'noun', gender: 'masculine', mass: true },
  cheese: { pos: 'noun', gender: 'masculine', mass: true },
  music: { pos: 'noun', gender: 'feminine', mass: true },
  paper: { pos: 'noun', gender: 'feminine', mass: true },
  fruit: { pos: 'noun', gender: 'feminine', mass: true },
  school: { pos: 'noun', gender: 'feminine', institutional: true },
  bed: { pos: 'noun', gender: 'masculine', institutional: true },
  home: { pos: 'noun', proper: true, institutional: true },
  hand: { pos: 'noun', gender: 'feminine', plural: 'mani' },
  hair: { pos: 'noun', gender: 'masculine', mass: true },
  heart: { pos: 'noun', gender: 'masculine' },
  car: { pos: 'noun', gender: 'feminine' },
  bag: { pos: 'noun', gender: 'masculine' },

  not: { pos: 'negation' },
}
