import type { Lexicon } from '../features'

/** Portuguese overlay: irregular verbs, gostar's preposition, mass nouns. */
export const portugueseLexicon: Lexicon = {
  hungry: { pos: 'adjective', sensation: 'fome' },
  thirsty: { pos: 'adjective', sensation: 'sede' },
  cold: { pos: 'adjective', sensation: 'frio' },
  hot: { pos: 'adjective', sensation: 'calor' },
  scared: { pos: 'adjective', sensation: 'medo' },
  i: { pos: 'pronoun', person: 1, number: 'sg', accusative: 'me' },
  you: { pos: 'pronoun', person: 2, number: 'sg', accusative: 'te' },
  we: { pos: 'pronoun', person: 1, number: 'pl', accusative: 'nos' },
  he: { pos: 'pronoun', person: 3, number: 'sg', accusative: 'o' },
  she: { pos: 'pronoun', person: 3, number: 'sg', accusative: 'a' },
  they: { pos: 'pronoun', person: 3, number: 'pl', accusative: 'os' },
  me: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'acc', accusative: 'me' },
  my: { pos: 'pronoun', person: 1, number: 'sg', pronounCase: 'poss', feminine: 'minha' },
  your: { pos: 'pronoun', person: 2, number: 'sg', pronounCase: 'poss', feminine: 'tua' },

  a: { pos: 'determiner', determinerKind: 'indefinite' },
  the: { pos: 'determiner', determinerKind: 'definite' },
  this: { pos: 'determiner', determinerKind: 'demonstrative' },
  that: { pos: 'determiner', determinerKind: 'demonstrative' },
  some: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  one: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'sg' },
  two: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  three: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  many: { pos: 'determiner', determinerKind: 'quantifier', forcesNumber: 'pl' },
  little: { pos: 'determiner', determinerKind: 'quantifier' },
  big: { pos: 'adjective' },

  want: { pos: 'verb', forms: { '1sg': 'quero', '2sg': 'queres', '3sg': 'quer', '1pl': 'queremos', '3pl': 'querem', past: 'queria' } },
  // gostar takes "de": "gosto de pão", contracting to "do pão" with an article.
  like: { pos: 'verb', objectPreposition: 'de' },
  have: { pos: 'verb', forms: { '1sg': 'tenho', '2sg': 'tens', '3sg': 'tem', '1pl': 'temos', '3pl': 'têm' } },
  go: { pos: 'verb', forms: { '1sg': 'vou', '2sg': 'vais', '3sg': 'vai', '1pl': 'vamos', '3pl': 'vão' } },
  come: { pos: 'verb', forms: { '1sg': 'venho', '2sg': 'vens', '3sg': 'vem', '1pl': 'vimos', '3pl': 'vêm' } },
  see: { pos: 'verb', forms: { '1sg': 'vejo', '2sg': 'vês', '3sg': 'vê', '1pl': 'vemos', '3pl': 'veem' } },
  hear: { pos: 'verb', forms: { '1sg': 'ouço', '2sg': 'ouves', '3sg': 'ouve', '1pl': 'ouvimos', '3pl': 'ouvem' } },
  read: { pos: 'verb', forms: { '1sg': 'leio', '2sg': 'lês', '3sg': 'lê', '1pl': 'lemos', '3pl': 'leem' } },
  feel: { pos: 'verb', forms: { '1sg': 'sinto', '2sg': 'sentes', '3sg': 'sente', '1pl': 'sentimos', '3pl': 'sentem' } },
  sleep: { pos: 'verb', forms: { '1sg': 'durmo', '2sg': 'dormes', '3sg': 'dorme', '1pl': 'dormimos', '3pl': 'dormem' } },

  apple: { pos: 'noun', gender: 'feminine', plural: 'maçãs' },
  water: { pos: 'noun', gender: 'feminine', mass: true },
  milk: { pos: 'noun', gender: 'masculine', mass: true },
  juice: { pos: 'noun', gender: 'masculine', mass: true },
  tea: { pos: 'noun', gender: 'masculine', mass: true },
  bread: { pos: 'noun', gender: 'masculine', mass: true },
  rice: { pos: 'noun', gender: 'masculine', mass: true },
  cheese: { pos: 'noun', gender: 'masculine', mass: true },
  music: { pos: 'noun', gender: 'feminine', mass: true },
  paper: { pos: 'noun', gender: 'masculine', mass: true },
  fruit: { pos: 'noun', gender: 'feminine', mass: true },
  school: { pos: 'noun', gender: 'feminine', institutional: true },
  bed: { pos: 'noun', gender: 'feminine', institutional: true },
  home: { pos: 'noun', proper: true, institutional: true },
  hand: { pos: 'noun', gender: 'feminine' },
  hair: { pos: 'noun', gender: 'masculine', mass: true },
  heart: { pos: 'noun', gender: 'masculine' },
  car: { pos: 'noun', gender: 'masculine' },
  bus: { pos: 'noun', gender: 'masculine' },

  not: { pos: 'negation' },
}
