// Generated by tools/generate-talk-packs-index.mjs — do not edit.
//
// One dynamic import per locale, so a bundler gives each pack its own chunk and an
// app loads only the language in front of the child — while still carrying all of
// them, because none of this should need the network.

import type { LanguagePack } from '@tiko/talk-types'

/** Every locale that has a pack. */
export const packLocales = ['af', 'ar', 'be', 'bg', 'bn', 'bs', 'ca', 'cnr', 'cs', 'cy', 'da', 'de', 'el', 'en', 'es', 'et', 'eu', 'fi', 'fr', 'fy', 'ga', 'gl', 'hi', 'hr', 'hu', 'hy', 'id', 'is', 'it', 'ja', 'ka', 'ko', 'lb', 'lt', 'lv', 'mk', 'ms', 'mt', 'nb', 'nl', 'pap', 'pl', 'pt', 'ro', 'ru', 'sk', 'sl', 'sq', 'sr', 'sv', 'tr', 'uk', 'vi', 'zh'] as const

export type PackLocale = typeof packLocales[number]

/** The loaders, one chunk each. */
const loaders: Record<string, () => Promise<{ default: unknown }>> = {
  "af": () => import('../data/af-v1.json'),
  "ar": () => import('../data/ar-v1.json'),
  "be": () => import('../data/be-v1.json'),
  "bg": () => import('../data/bg-v1.json'),
  "bn": () => import('../data/bn-v1.json'),
  "bs": () => import('../data/bs-v1.json'),
  "ca": () => import('../data/ca-v1.json'),
  "cnr": () => import('../data/cnr-v1.json'),
  "cs": () => import('../data/cs-v1.json'),
  "cy": () => import('../data/cy-v1.json'),
  "da": () => import('../data/da-v1.json'),
  "de": () => import('../data/de-v1.json'),
  "el": () => import('../data/el-v1.json'),
  "en": () => import('../data/en-v1.json'),
  "es": () => import('../data/es-v1.json'),
  "et": () => import('../data/et-v1.json'),
  "eu": () => import('../data/eu-v1.json'),
  "fi": () => import('../data/fi-v1.json'),
  "fr": () => import('../data/fr-v1.json'),
  "fy": () => import('../data/fy-v1.json'),
  "ga": () => import('../data/ga-v1.json'),
  "gl": () => import('../data/gl-v1.json'),
  "hi": () => import('../data/hi-v1.json'),
  "hr": () => import('../data/hr-v1.json'),
  "hu": () => import('../data/hu-v1.json'),
  "hy": () => import('../data/hy-v1.json'),
  "id": () => import('../data/id-v1.json'),
  "is": () => import('../data/is-v1.json'),
  "it": () => import('../data/it-v1.json'),
  "ja": () => import('../data/ja-v1.json'),
  "ka": () => import('../data/ka-v1.json'),
  "ko": () => import('../data/ko-v1.json'),
  "lb": () => import('../data/lb-v1.json'),
  "lt": () => import('../data/lt-v1.json'),
  "lv": () => import('../data/lv-v1.json'),
  "mk": () => import('../data/mk-v1.json'),
  "ms": () => import('../data/ms-v1.json'),
  "mt": () => import('../data/mt-v1.json'),
  "nb": () => import('../data/nb-v1.json'),
  "nl": () => import('../data/nl-v1.json'),
  "pap": () => import('../data/pap-v1.json'),
  "pl": () => import('../data/pl-v1.json'),
  "pt": () => import('../data/pt-v1.json'),
  "ro": () => import('../data/ro-v1.json'),
  "ru": () => import('../data/ru-v1.json'),
  "sk": () => import('../data/sk-v1.json'),
  "sl": () => import('../data/sl-v1.json'),
  "sq": () => import('../data/sq-v1.json'),
  "sr": () => import('../data/sr-v1.json'),
  "sv": () => import('../data/sv-v1.json'),
  "tr": () => import('../data/tr-v1.json'),
  "uk": () => import('../data/uk-v1.json'),
  "vi": () => import('../data/vi-v1.json'),
  "zh": () => import('../data/zh-v1.json'),
}

/** True where a pack exists for this locale. */
export function hasPack(locale: string): boolean {
  return language(locale) in loaders
}

/**
 * Loads one language pack. The locale may carry a region ("nl-BE"); only the
 * language part is used, and an unknown one throws rather than resolving to
 * English silently — a caller that wants a fallback should ask for it.
 */
export async function loadPack(locale: string): Promise<LanguagePack> {
  const code = language(locale)
  const loader = loaders[code]
  if (!loader) throw new Error(`no Talk pack for locale "${locale}"`)
  const module = await loader()
  return module.default as LanguagePack
}

/** The language part of a locale, lowercased. */
function language(locale: string): string {
  return locale.split('-')[0].toLowerCase()
}

/** The shared media map: one image per concept id, across every language. */
export async function loadMediaMap(): Promise<Record<string, string>> {
  const module = await import('../data/media-map.json')
  return module.default as Record<string, string>
}
