// Generated by tools/generate-tiko-colors.mjs from packages/ui/tiko-colors.json.
// Do not edit this file directly.

export type TikoColorName = 'red' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple' | 'pink' | 'brown' | 'black' | 'white' | 'gray' | 'beige' | 'cyan' | 'teal' | 'navy' | 'lime' | 'magenta' | 'maroon' | 'gold' | 'silver'
