// Generated by tools/generate-locales.mjs — do not edit.
// The languages Tiko offers live in tools/locales.mjs, which writes this file
// and its Swift counterpart so the two platforms cannot drift.

import Foundation

public extension TikoLanguage {
    /// Every language the app offers, in picker order.
    static let allLanguages: [TikoLanguage] = [
        TikoLanguage(id: "en", title: "English", nativeTitle: "English", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "nl", title: "Dutch", nativeTitle: "Nederlands", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "de", title: "German", nativeTitle: "Deutsch", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "fr", title: "French", nativeTitle: "Français", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "es", title: "Spanish", nativeTitle: "Español", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "pt", title: "Portuguese", nativeTitle: "Português", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "it", title: "Italian", nativeTitle: "Italiano", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "mt", title: "Maltese", nativeTitle: "Malti", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .full),
        TikoLanguage(id: "ja", title: "Japanese", nativeTitle: "日本語", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "zh", title: "Chinese", nativeTitle: "中文", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ko", title: "Korean", nativeTitle: "한국어", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ar", title: "Arabic", nativeTitle: "العربية", isRightToLeft: true, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "hy", title: "Armenian", nativeTitle: "Հայերեն", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "id", title: "Indonesian", nativeTitle: "Bahasa Indonesia", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ms", title: "Malay", nativeTitle: "Bahasa Melayu", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "vi", title: "Vietnamese", nativeTitle: "Tiếng Việt", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "af", title: "Afrikaans", nativeTitle: "Afrikaans", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "sv", title: "Swedish", nativeTitle: "Svenska", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "da", title: "Danish", nativeTitle: "Dansk", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "nb", title: "Norwegian", nativeTitle: "Norsk", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "is", title: "Icelandic", nativeTitle: "Íslenska", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "fy", title: "West Frisian", nativeTitle: "Frysk", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "lb", title: "Luxembourgish", nativeTitle: "Lëtzebuergesch", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ca", title: "Catalan", nativeTitle: "Català", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "gl", title: "Galician", nativeTitle: "Galego", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ro", title: "Romanian", nativeTitle: "Română", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "pap", title: "Papiamentu", nativeTitle: "Papiamentu", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ru", title: "Russian", nativeTitle: "Русский", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "uk", title: "Ukrainian", nativeTitle: "Українська", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "be", title: "Belarusian", nativeTitle: "Беларуская", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "pl", title: "Polish", nativeTitle: "Polski", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "cs", title: "Czech", nativeTitle: "Čeština", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "sk", title: "Slovak", nativeTitle: "Slovenčina", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "sl", title: "Slovenian", nativeTitle: "Slovenščina", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "hr", title: "Croatian", nativeTitle: "Hrvatski", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "sr", title: "Serbian", nativeTitle: "Српски", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "bs", title: "Bosnian", nativeTitle: "Bosanski", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "cnr", title: "Montenegrin", nativeTitle: "Crnogorski", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "bg", title: "Bulgarian", nativeTitle: "Български", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "mk", title: "Macedonian", nativeTitle: "Македонски", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "lt", title: "Lithuanian", nativeTitle: "Lietuvių", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "lv", title: "Latvian", nativeTitle: "Latviešu", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "fi", title: "Finnish", nativeTitle: "Suomi", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "et", title: "Estonian", nativeTitle: "Eesti", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "hu", title: "Hungarian", nativeTitle: "Magyar", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "cy", title: "Welsh", nativeTitle: "Cymraeg", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ga", title: "Irish", nativeTitle: "Gaeilge", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "bn", title: "Bengali", nativeTitle: "বাংলা", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "hi", title: "Hindi", nativeTitle: "हिन्दी", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "el", title: "Greek", nativeTitle: "Ελληνικά", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "sq", title: "Albanian", nativeTitle: "Shqip", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "tr", title: "Turkish", nativeTitle: "Türkçe", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "eu", title: "Basque", nativeTitle: "Euskara", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
        TikoLanguage(id: "ka", title: "Georgian", nativeTitle: "ქართული", isRightToLeft: false, hasTalkGrammar: true, interfaceCoverage: .core),
    ]

    /// The codes `TikoDeviceDefaults` matches the device language against.
    static var allLanguageCodes: [String] { allLanguages.map(\.id) }
}
