// Generated by tools/generate-arlez-projects.mjs — do not edit.
// Source of truth: packages/tikokit-ios/arlez-projects.json
//
// A product ID selects a destination in Arlez. It is not a credential, which is
// why it can ship inside the app. The Arlez API key is a secret and is not here.

public enum TikoArlezProjects {

    /// Bundle identifier to Arlez product ID, for the iOS projects only.
    public static let productIDsByBundleID: [String: String] = [
        "mt.tiko.cards": "pub_f06a4335bca6b9638581aae8", // Cards · iOS
        "mt.tiko.first": "pub_013e04a614c8def7da07fbaa", // First · iOS
        "mt.tiko.radio": "pub_bfafa020bf7e198ce9944463", // Radio · iOS
        "mt.tiko.say": "pub_19cd8aac7f2c86138e663b27", // Say · iOS
        "mt.tiko.sum": "pub_f4503538e30f4951705bda68", // Sum · iOS
        "mt.tiko.talk": "pub_0a57f35efd52b775f3ad2e3d", // Talk · iOS
        "mt.tiko.timer": "pub_bb304f243d76a12c10fc5328", // Timer · iOS
        "mt.tiko.type": "pub_b04a93683710e1ed21122c2d", // Type · iOS
        "mt.tiko.write": "pub_033d281e0b66caf0eee5dc01", // Write · iOS
        "mt.tiko.yesno": "pub_c551cfdf0ab6fa82b903ab4e", // Yes No · iOS
    ]

    /// The product ID for a bundle identifier, or nil when the app has no Arlez
    /// project yet — Support hides itself rather than offering a form that
    /// cannot be delivered.
    public static func productID(forBundleID bundleID: String?) -> String? {
        guard let bundleID else { return nil }
        return productIDsByBundleID[bundleID]
    }
}
