import Foundation

/// What Support says, in the six languages the rest of the shared sheets cover.
///
/// The category names and field labels are not here — those come from Arlez, in
/// whatever language they were written. Only the surrounding chrome is
/// translated, so a new category never leaves a raw identifier on screen.
public struct TikoSupportLabels: Sendable {
    public var support = "Support"
    public var subtitle = "Tell us what happened, or what would help."
    public var whatIsIt = "What is it about?"
    public var previous = "Your earlier messages"
    public var optional = "optional"
    public var email = "Your email"
    public var emailHint = "Only so we can answer you. Leave it out if you would rather not."
    public var send = "Send"
    public var done = "Done"
    public var back = "Back"
    public var tryAgain = "Try again"
    public var sentTitle = "Thank you"
    public var sentBody = "Your message reached us. You can read any reply here."
    public var readConversation = "Read the conversation"
    public var noReplyYet = "No reply yet. We read everything."
    public var reply = "Write a reply"
    public var closed = "This conversation is closed."
    public var unavailable = "Support needs a connection. Try again when you are back online."
    public var couldNotSend = "That did not send. Please try again."
    public var couldNotLoad = "That did not load. Please try again."
    public var fillRequired = "Please fill in the required field."

    public static func forLanguage(_ languageID: String) -> TikoSupportLabels {
        var l = TikoSupportLabels()
        switch languageID {
        case "nl":
            l.support = "Support"
            l.subtitle = "Vertel wat er gebeurde, of wat zou helpen."
            l.whatIsIt = "Waar gaat het over?"
            l.previous = "Je eerdere berichten"
            l.optional = "optioneel"
            l.email = "Je e-mailadres"
            l.emailHint = "Alleen om je te kunnen antwoorden. Laat het weg als je dat liever hebt."
            l.send = "Versturen"
            l.done = "Klaar"
            l.back = "Terug"
            l.tryAgain = "Opnieuw proberen"
            l.sentTitle = "Bedankt"
            l.sentBody = "Je bericht is aangekomen. Een antwoord lees je hier."
            l.readConversation = "Gesprek lezen"
            l.noReplyYet = "Nog geen antwoord. We lezen alles."
            l.reply = "Schrijf een antwoord"
            l.closed = "Dit gesprek is gesloten."
            l.unavailable = "Support heeft internet nodig. Probeer het opnieuw als je weer online bent."
            l.couldNotSend = "Versturen is niet gelukt. Probeer het opnieuw."
            l.couldNotLoad = "Laden is niet gelukt. Probeer het opnieuw."
            l.fillRequired = "Vul het verplichte veld in."
        case "de":
            l.subtitle = "Erzähl uns, was passiert ist oder was helfen würde."
            l.whatIsIt = "Worum geht es?"
            l.previous = "Deine früheren Nachrichten"
            l.optional = "optional"
            l.email = "Deine E-Mail-Adresse"
            l.emailHint = "Nur damit wir antworten können. Lass es weg, wenn du lieber möchtest."
            l.send = "Senden"
            l.done = "Fertig"
            l.back = "Zurück"
            l.tryAgain = "Erneut versuchen"
            l.sentTitle = "Danke"
            l.sentBody = "Deine Nachricht ist angekommen. Eine Antwort liest du hier."
            l.readConversation = "Gespräch lesen"
            l.noReplyYet = "Noch keine Antwort. Wir lesen alles."
            l.reply = "Antwort schreiben"
            l.closed = "Dieses Gespräch ist geschlossen."
            l.unavailable = "Support braucht eine Verbindung. Versuch es erneut, wenn du wieder online bist."
            l.couldNotSend = "Das ging nicht raus. Bitte versuch es erneut."
            l.couldNotLoad = "Das konnte nicht geladen werden. Bitte versuch es erneut."
            l.fillRequired = "Bitte fülle das Pflichtfeld aus."
        case "fr":
            l.subtitle = "Dites-nous ce qui s'est passé, ou ce qui aiderait."
            l.whatIsIt = "De quoi s'agit-il ?"
            l.previous = "Vos messages précédents"
            l.optional = "facultatif"
            l.email = "Votre e-mail"
            l.emailHint = "Uniquement pour pouvoir vous répondre. Laissez vide si vous préférez."
            l.send = "Envoyer"
            l.done = "Terminé"
            l.back = "Retour"
            l.tryAgain = "Réessayer"
            l.sentTitle = "Merci"
            l.sentBody = "Votre message nous est parvenu. Vous lirez la réponse ici."
            l.readConversation = "Lire la conversation"
            l.noReplyYet = "Pas encore de réponse. Nous lisons tout."
            l.reply = "Écrire une réponse"
            l.closed = "Cette conversation est close."
            l.unavailable = "Le support a besoin d'une connexion. Réessayez une fois en ligne."
            l.couldNotSend = "L'envoi a échoué. Veuillez réessayer."
            l.couldNotLoad = "Le chargement a échoué. Veuillez réessayer."
            l.fillRequired = "Veuillez remplir le champ obligatoire."
        case "es":
            l.subtitle = "Cuéntanos qué ha pasado, o qué ayudaría."
            l.whatIsIt = "¿De qué se trata?"
            l.previous = "Tus mensajes anteriores"
            l.optional = "opcional"
            l.email = "Tu correo"
            l.emailHint = "Solo para poder responderte. Déjalo vacío si lo prefieres."
            l.send = "Enviar"
            l.done = "Listo"
            l.back = "Atrás"
            l.tryAgain = "Reintentar"
            l.sentTitle = "Gracias"
            l.sentBody = "Tu mensaje nos ha llegado. Aquí leerás la respuesta."
            l.readConversation = "Leer la conversación"
            l.noReplyYet = "Aún no hay respuesta. Lo leemos todo."
            l.reply = "Escribe una respuesta"
            l.closed = "Esta conversación está cerrada."
            l.unavailable = "El soporte necesita conexión. Inténtalo cuando vuelvas a estar en línea."
            l.couldNotSend = "No se ha enviado. Inténtalo de nuevo."
            l.couldNotLoad = "No se ha cargado. Inténtalo de nuevo."
            l.fillRequired = "Rellena el campo obligatorio."
        case "mt":
            l.subtitle = "Għidilna x'ġara, jew x'jgħin."
            l.whatIsIt = "Fuq xiex hu?"
            l.previous = "Il-messaġġi ta' qabel tiegħek"
            l.optional = "mhux obbligatorju"
            l.email = "L-email tiegħek"
            l.emailHint = "Biss biex inkunu nistgħu nwieġbuk. Ħallih vojt jekk tippreferi."
            l.send = "Ibgħat"
            l.done = "Lest"
            l.back = "Lura"
            l.tryAgain = "Erġa' pprova"
            l.sentTitle = "Grazzi"
            l.sentBody = "Il-messaġġ tiegħek wasal. Kull tweġiba taqraha hawn."
            l.readConversation = "Aqra l-konverżazzjoni"
            l.noReplyYet = "Għadha ma waslitx tweġiba. Naqraw kollox."
            l.reply = "Ikteb tweġiba"
            l.closed = "Din il-konverżazzjoni ngħalqet."
            l.unavailable = "Support jeħtieġ konnessjoni. Erġa' pprova meta tkun online."
            l.couldNotSend = "Ma ntbagħatx. Jekk jogħġbok erġa' pprova."
            l.couldNotLoad = "Ma tgħabbiex. Jekk jogħġbok erġa' pprova."
            l.fillRequired = "Jekk jogħġbok imla l-qasam obbligatorju."
        default:
            break
        }
        return l
    }
}
