import Foundation
import JavaScriptCore

/// A word a child tapped, on its way to becoming a sentence.
public struct TikoSentenceWord: Codable, Equatable, Sendable {
    public let id: String
    public let text: String
    public let pos: String
    public let category: String

    public init(id: String, text: String, pos: String, category: String) {
        self.id = id
        self.text = text
        self.pos = pos
        self.category = category
    }
}

/// What the realizer made of those words, and why.
public struct TikoSentence: Equatable, Sendable {
    /// The finished sentence, punctuated: "Ik wil een appel."
    public let text: String
    /// The same sentence without its terminator, for a strip still being built.
    public let strip: String
    /// What the realizer did and where it had to guess. Worth logging, not showing.
    public let notes: [String]
    /// Words the realizer added that no tile provided — articles, auxiliaries.
    public let inserted: [String]

    public static let empty = TikoSentence(text: "", strip: "", notes: [], inserted: [])
}

/// A language pack: the tiles a child chooses from, and the grammar behind them.
public struct TikoTalkPack: Codable, Sendable {
    public struct Word: Codable, Sendable {
        public let id: String
        public let text: String
        public let pos: String
        public let category: String
        public let frequency: Int?
        public let icon: String?
        public let image: String?
    }

    public struct Template: Codable, Sendable {
        public let id: String
        public let pattern: String
        public let category: String
        public let icon: String?
    }

    public struct Grammar: Codable, Sendable {
        public let wordOrder: String?
        public let validTransitions: [String: [String]]?
    }

    public let locale: String
    public let version: Int
    public let words: [Word]
    public let templates: [Template]
    public let grammar: Grammar?
}

/**
 Sentences, on the device.

 Talk's grammar is one implementation — `packages/talk-realizer`, 54 languages and
 1,300 tests — and this runs *that*, rather than a Swift retelling of it. The bundle
 in `Resources/talk-realizer.js` is generated by
 `tools/generate-talk-realizer-bundle.mjs` and evaluated in JavaScriptCore, which
 ships with iOS. Nothing is fetched and nothing is downloaded: a child on a train in
 a tunnel gets the same sentence as a child at home.

 A Swift port was the alternative. It would mean maintaining fifty-four languages of
 morphology twice and discovering the divergence in production, in a language nobody
 on the team reads. This repo already generates Swift from TypeScript for app configs,
 colours and locales for the same reason.

 Usage:

 ```swift
 let builder = TikoSentenceBuilder.shared
 let pack = try builder.pack(for: "nl")
 let sentence = builder.sentence(for: chosen, locale: "nl")
 stripLabel.text = sentence.strip     // "Ik wil een appel"
 speak(sentence.text)                 // "Ik wil een appel."
 ```
 */
public final class TikoSentenceBuilder {
    public static let shared = TikoSentenceBuilder()

    private let queue = DispatchQueue(label: "org.tiko.sentence")
    private var context: JSContext?
    private var packs: [String: TikoTalkPack] = [:]
    private var loadFailure: String?

    private init() {}

    // MARK: - Sentences

    /// The sentence these tiles make in this language.
    ///
    /// `customWordIds` are words the child added themselves — almost always names,
    /// which take no article: "I want Sil", not "I want a Sil".
    public func sentence(
        for words: [TikoSentenceWord],
        locale: String,
        customWordIds: Set<String> = [],
        negated: Bool = false,
        speakerGender: String? = nil
    ) -> TikoSentence {
        guard !words.isEmpty else { return .empty }

        var payload: [String: Any] = [
            "words": words.map { ["id": $0.id, "text": $0.text, "pos": $0.pos, "category": $0.category] },
            "locale": locale,
        ]
        if !customWordIds.isEmpty { payload["custom"] = Array(customWordIds) }
        if negated { payload["negated"] = true }
        if let speakerGender { payload["speakerGender"] = speakerGender }

        guard
            let data = try? JSONSerialization.data(withJSONObject: payload),
            let json = String(data: data, encoding: .utf8)
        else { return fallback(words) }

        return queue.sync {
            guard let context = prepared() else { return fallback(words) }
            guard
                let function = context.objectForKeyedSubscript("tikoRealize"),
                let result = function.call(withArguments: [json]),
                let text = result.toString(),
                let parsed = decode(text)
            else { return fallback(words) }
            return parsed
        }
    }

    /// The languages the bundle has grammar for. Empty if it failed to load.
    public func supportedLanguages() -> [String] {
        queue.sync {
            guard
                let context = prepared(),
                let function = context.objectForKeyedSubscript("tikoRealizerLanguages"),
                let result = function.call(withArguments: []),
                let json = result.toString(),
                let data = json.data(using: .utf8),
                let codes = try? JSONDecoder().decode([String].self, from: data)
            else { return [] }
            return codes
        }
    }

    // MARK: - Packs

    /// The pack for a language, from the app bundle. Kept after the first read.
    public func pack(for locale: String) throws -> TikoTalkPack {
        let code = Self.language(locale)
        if let cached = queue.sync(execute: { packs[code] }) { return cached }

        guard let url = Bundle.module.url(forResource: "\(code)-v1", withExtension: "json", subdirectory: "talk-packs")
            ?? Bundle.module.url(forResource: "\(code)-v1", withExtension: "json")
        else {
            throw TikoSentenceError.noPack(code)
        }
        let data = try Data(contentsOf: url)
        let pack = try JSONDecoder().decode(TikoTalkPack.self, from: data)
        queue.sync { packs[code] = pack }
        return pack
    }

    /// True where a pack for this language ships with the app.
    public func hasPack(for locale: String) -> Bool {
        let code = Self.language(locale)
        if queue.sync(execute: { packs[code] != nil }) { return true }
        return Bundle.module.url(forResource: "\(code)-v1", withExtension: "json", subdirectory: "talk-packs") != nil
            || Bundle.module.url(forResource: "\(code)-v1", withExtension: "json") != nil
    }

    /// Which parts of speech may follow what the child has chosen.
    public func validNext(after chosen: [TikoSentenceWord], in pack: TikoTalkPack) -> [String] {
        guard let transitions = pack.grammar?.validTransitions else { return [] }
        guard let last = chosen.last else { return Array(transitions.keys) }
        return transitions[last.pos] ?? []
    }

    // MARK: - Private

    /// Loads and evaluates the bundle once. Nil if it is missing or throws.
    private func prepared() -> JSContext? {
        if let context { return context }
        if loadFailure != nil { return nil }

        guard
            let url = Bundle.module.url(forResource: "talk-realizer", withExtension: "js"),
            let source = try? String(contentsOf: url, encoding: .utf8)
        else {
            loadFailure = "talk-realizer.js is missing from the bundle"
            return nil
        }

        let created = JSContext()
        created?.exceptionHandler = { [weak self] _, exception in
            self?.loadFailure = exception?.toString() ?? "unknown JavaScript exception"
        }
        created?.evaluateScript(source)
        if loadFailure != nil { return nil }
        context = created
        return created
    }

    private func decode(_ json: String) -> TikoSentence? {
        guard
            let data = json.data(using: .utf8),
            let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return nil }
        if let error = object["error"] as? String {
            loadFailure = error
            return nil
        }
        guard let text = object["text"] as? String else { return nil }
        return TikoSentence(
            text: text,
            strip: object["strip"] as? String ?? text,
            notes: object["notes"] as? [String] ?? [],
            inserted: object["inserted"] as? [String] ?? []
        )
    }

    /// What the app did before the realizer existed: the tiles, joined. Reached only
    /// if the bundle is broken, which is a build problem rather than a runtime one —
    /// but a child should still get their sentence.
    private func fallback(_ words: [TikoSentenceWord]) -> TikoSentence {
        let joined = words.map(\.text).joined(separator: " ")
        let capitalized = joined.isEmpty ? "" : joined.prefix(1).uppercased() + joined.dropFirst()
        return TikoSentence(
            text: capitalized.isEmpty ? "" : "\(capitalized).",
            strip: capitalized,
            notes: ["the realizer bundle did not load: tiles joined as-is"],
            inserted: []
        )
    }

    private static func language(_ locale: String) -> String {
        locale.split(separator: "-").first?.lowercased() ?? locale.lowercased()
    }
}

public enum TikoSentenceError: Error, LocalizedError {
    case noPack(String)

    public var errorDescription: String? {
        switch self {
        case .noPack(let code): "No Talk pack for \"\(code)\" ships with this app."
        }
    }
}
