import Foundation

// Offline fallback only — authoritative defaults come from content.tikoapi.org/v1/cards/collections.
let defaultCardCollections: [CardCollection] = [
    CardCollection(id: "__default_animals", title: "Animals", color: "green", order: 1, mediaCategories: ["animals"], cards: [
        CommunicationCard(id: "__default_animals_cat", title: "Cat", speech: "Cat", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_dog", title: "Dog", speech: "Dog", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_bird", title: "Bird", speech: "Bird", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_fish", title: "Fish", speech: "Fish", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_horse", title: "Horse", speech: "Horse", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_elephant", title: "Elephant", speech: "Elephant", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_lion", title: "Lion", speech: "Lion", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_monkey", title: "Monkey", speech: "Monkey", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_rabbit", title: "Rabbit", speech: "Rabbit", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_bear", title: "Bear", speech: "Bear", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_cow", title: "Cow", speech: "Cow", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_animals_pig", title: "Pig", speech: "Pig", imageURL: nil, color: "green"),
    ]),
    CardCollection(id: "__default_food", title: "Food", color: "orange", order: 2, mediaCategories: ["food"], cards: [
        CommunicationCard(id: "__default_food_apple", title: "Apple", speech: "Apple", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_banana", title: "Banana", speech: "Banana", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_bread", title: "Bread", speech: "Bread", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_rice", title: "Rice", speech: "Rice", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_pasta", title: "Pasta", speech: "Pasta", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_pizza", title: "Pizza", speech: "Pizza", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_soup", title: "Soup", speech: "Soup", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_carrot", title: "Carrot", speech: "Carrot", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_egg", title: "Egg", speech: "Egg", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_potato", title: "Potato", speech: "Potato", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_tomato", title: "Tomato", speech: "Tomato", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_food_cheese", title: "Cheese", speech: "Cheese", imageURL: nil, color: "orange"),
    ]),
    CardCollection(id: "__default_snacks", title: "Snacks", color: "orange", order: 3, mediaCategories: ["snacks", "food-snacks"], cards: [
        CommunicationCard(id: "__default_snacks_cookie", title: "Cookie", speech: "Cookie", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_chips", title: "Chips", speech: "Chips", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_crackers", title: "Crackers", speech: "Crackers", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_popcorn", title: "Popcorn", speech: "Popcorn", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_nuts", title: "Nuts", speech: "Nuts", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_yogurt", title: "Yogurt", speech: "Yogurt", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_fruit", title: "Fruit", speech: "Fruit", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_chocolate", title: "Chocolate", speech: "Chocolate", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_pretzels", title: "Pretzels", speech: "Pretzels", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_snacks_granola", title: "Granola Bar", speech: "Granola Bar", imageURL: nil, color: "orange"),
    ]),
    CardCollection(id: "__default_drinks", title: "Drinks", color: "blue", order: 4, mediaCategories: ["drinks"], cards: [
        CommunicationCard(id: "__default_drinks_water", title: "Water", speech: "Water", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_milk", title: "Milk", speech: "Milk", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_juice", title: "Juice", speech: "Juice", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_tea", title: "Tea", speech: "Tea", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_coffee", title: "Coffee", speech: "Coffee", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_lemonade", title: "Lemonade", speech: "Lemonade", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_soda", title: "Soda", speech: "Soda", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_smoothie", title: "Smoothie", speech: "Smoothie", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_drinks_hot_chocolate", title: "Hot Chocolate", speech: "Hot Chocolate", imageURL: nil, color: "blue"),
    ]),
    CardCollection(id: "__default_colors", title: "Colors", color: "purple", order: 5, mediaCategories: ["colors"], cards: [
        CommunicationCard(id: "__default_colors_red", title: "Red", speech: "Red", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_blue", title: "Blue", speech: "Blue", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_green", title: "Green", speech: "Green", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_yellow", title: "Yellow", speech: "Yellow", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_orange", title: "Orange", speech: "Orange", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_purple", title: "Purple", speech: "Purple", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_pink", title: "Pink", speech: "Pink", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_black", title: "Black", speech: "Black", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_white", title: "White", speech: "White", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_brown", title: "Brown", speech: "Brown", imageURL: nil, color: "purple"),
        CommunicationCard(id: "__default_colors_grey", title: "Grey", speech: "Grey", imageURL: nil, color: "purple"),
    ]),
    CardCollection(id: "__default_emotions", title: "Emotions", color: "red", order: 6, mediaCategories: ["emotions", "feelings"], cards: [
        CommunicationCard(id: "__default_emotions_happy", title: "Happy", speech: "Happy", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_sad", title: "Sad", speech: "Sad", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_angry", title: "Angry", speech: "Angry", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_scared", title: "Scared", speech: "Scared", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_surprised", title: "Surprised", speech: "Surprised", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_tired", title: "Tired", speech: "Tired", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_excited", title: "Excited", speech: "Excited", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_calm", title: "Calm", speech: "Calm", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_confused", title: "Confused", speech: "Confused", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_loved", title: "Loved", speech: "Loved", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_worried", title: "Worried", speech: "Worried", imageURL: nil, color: "red"),
        CommunicationCard(id: "__default_emotions_bored", title: "Bored", speech: "Bored", imageURL: nil, color: "red"),
    ]),
    CardCollection(id: "__default_transport", title: "Transport", color: "gray", order: 7, mediaCategories: ["transport", "vehicles"], cards: [
        CommunicationCard(id: "__default_transport_car", title: "Car", speech: "Car", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_bus", title: "Bus", speech: "Bus", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_train", title: "Train", speech: "Train", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_plane", title: "Plane", speech: "Plane", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_bike", title: "Bike", speech: "Bike", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_boat", title: "Boat", speech: "Boat", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_truck", title: "Truck", speech: "Truck", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_motorcycle", title: "Motorcycle", speech: "Motorcycle", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_helicopter", title: "Helicopter", speech: "Helicopter", imageURL: nil, color: "gray"),
        CommunicationCard(id: "__default_transport_taxi", title: "Taxi", speech: "Taxi", imageURL: nil, color: "gray"),
    ]),
    CardCollection(id: "__default_body", title: "Body", color: "brown", order: 8, mediaCategories: ["body", "body-parts"], cards: [
        CommunicationCard(id: "__default_body_head", title: "Head", speech: "Head", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_arms", title: "Arms", speech: "Arms", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_legs", title: "Legs", speech: "Legs", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_hands", title: "Hands", speech: "Hands", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_feet", title: "Feet", speech: "Feet", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_eyes", title: "Eyes", speech: "Eyes", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_ears", title: "Ears", speech: "Ears", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_nose", title: "Nose", speech: "Nose", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_mouth", title: "Mouth", speech: "Mouth", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_hair", title: "Hair", speech: "Hair", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_fingers", title: "Fingers", speech: "Fingers", imageURL: nil, color: "brown"),
        CommunicationCard(id: "__default_body_toes", title: "Toes", speech: "Toes", imageURL: nil, color: "brown"),
    ]),
    CardCollection(id: "__default_numbers", title: "Numbers", color: "blue", order: 9, mediaCategories: ["numbers"], cards: [
        CommunicationCard(id: "__default_numbers_1", title: "1", speech: "one", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_2", title: "2", speech: "two", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_3", title: "3", speech: "three", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_4", title: "4", speech: "four", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_5", title: "5", speech: "five", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_6", title: "6", speech: "six", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_7", title: "7", speech: "seven", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_8", title: "8", speech: "eight", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_9", title: "9", speech: "nine", imageURL: nil, color: "blue"),
        CommunicationCard(id: "__default_numbers_10", title: "10", speech: "ten", imageURL: nil, color: "blue"),
    ]),
    CardCollection(id: "__default_letters", title: "Letters", color: "teal", order: 10, mediaCategories: ["letters", "alphabet"], cards:
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ".map { l in
            CommunicationCard(id: "__default_letters_\(l.lowercased())", title: String(l), speech: String(l), imageURL: nil, color: "teal")
        }
    ),
    CardCollection(id: "__default_actions", title: "Actions", color: "magenta", order: 11, mediaCategories: ["actions", "verbs"], cards: [
        CommunicationCard(id: "__default_actions_eat", title: "Eat", speech: "Eat", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_drink", title: "Drink", speech: "Drink", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_sleep", title: "Sleep", speech: "Sleep", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_play", title: "Play", speech: "Play", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_walk", title: "Walk", speech: "Walk", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_run", title: "Run", speech: "Run", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_sit", title: "Sit", speech: "Sit", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_stand", title: "Stand", speech: "Stand", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_go", title: "Go", speech: "Go", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_stop", title: "Stop", speech: "Stop", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_help", title: "Help", speech: "Help", imageURL: nil, color: "magenta"),
        CommunicationCard(id: "__default_actions_come", title: "Come", speech: "Come", imageURL: nil, color: "magenta"),
    ]),
    CardCollection(id: "__default_people", title: "People", color: "orange", order: 12, mediaCategories: ["people", "family"], cards: [
        CommunicationCard(id: "__default_people_mom", title: "Mom", speech: "Mom", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_dad", title: "Dad", speech: "Dad", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_sister", title: "Sister", speech: "Sister", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_brother", title: "Brother", speech: "Brother", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_grandma", title: "Grandma", speech: "Grandma", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_grandpa", title: "Grandpa", speech: "Grandpa", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_baby", title: "Baby", speech: "Baby", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_friend", title: "Friend", speech: "Friend", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_teacher", title: "Teacher", speech: "Teacher", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_doctor", title: "Doctor", speech: "Doctor", imageURL: nil, color: "orange"),
        CommunicationCard(id: "__default_people_myself", title: "Myself", speech: "Myself", imageURL: nil, color: "orange"),
    ]),
    CardCollection(id: "__default_places", title: "Places", color: "cyan", order: 13, mediaCategories: ["places", "locations"], cards: [
        CommunicationCard(id: "__default_places_home", title: "Home", speech: "Home", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_school", title: "School", speech: "School", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_park", title: "Park", speech: "Park", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_store", title: "Store", speech: "Store", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_hospital", title: "Hospital", speech: "Hospital", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_library", title: "Library", speech: "Library", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_beach", title: "Beach", speech: "Beach", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_restaurant", title: "Restaurant", speech: "Restaurant", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_playground", title: "Playground", speech: "Playground", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_toilet", title: "Toilet", speech: "Toilet", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_bedroom", title: "Bedroom", speech: "Bedroom", imageURL: nil, color: "cyan"),
        CommunicationCard(id: "__default_places_kitchen", title: "Kitchen", speech: "Kitchen", imageURL: nil, color: "cyan"),
    ]),
    CardCollection(id: "__default_clothing", title: "Clothing", color: "lime", order: 14, mediaCategories: ["clothing", "clothes"], cards: [
        CommunicationCard(id: "__default_clothing_shirt", title: "Shirt", speech: "Shirt", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_pants", title: "Pants", speech: "Pants", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_shoes", title: "Shoes", speech: "Shoes", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_socks", title: "Socks", speech: "Socks", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_jacket", title: "Jacket", speech: "Jacket", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_dress", title: "Dress", speech: "Dress", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_hat", title: "Hat", speech: "Hat", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_coat", title: "Coat", speech: "Coat", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_gloves", title: "Gloves", speech: "Gloves", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_scarf", title: "Scarf", speech: "Scarf", imageURL: nil, color: "lime"),
        CommunicationCard(id: "__default_clothing_boots", title: "Boots", speech: "Boots", imageURL: nil, color: "lime"),
    ]),
    CardCollection(id: "__default_nature", title: "Nature", color: "green", order: 15, mediaCategories: ["nature", "weather"], cards: [
        CommunicationCard(id: "__default_nature_sun", title: "Sun", speech: "Sun", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_rain", title: "Rain", speech: "Rain", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_cloud", title: "Cloud", speech: "Cloud", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_tree", title: "Tree", speech: "Tree", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_flower", title: "Flower", speech: "Flower", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_grass", title: "Grass", speech: "Grass", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_snow", title: "Snow", speech: "Snow", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_wind", title: "Wind", speech: "Wind", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_mountain", title: "Mountain", speech: "Mountain", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_river", title: "River", speech: "River", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_star", title: "Star", speech: "Star", imageURL: nil, color: "green"),
        CommunicationCard(id: "__default_nature_moon", title: "Moon", speech: "Moon", imageURL: nil, color: "green"),
    ]),
]
