import Foundation

let defaultCardCollections: [CardCollection] = [
    CardCollection(
        id: "__default_animals",
        title: "Animals",
        colorHex: 0xFFB347,
        order: 0,
        mediaCategories: ["animals"],
        cards: [
            CommunicationCard(id: "animal_dog", title: "Dog", speech: "Dog", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_cat", title: "Cat", speech: "Cat", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_bird", title: "Bird", speech: "Bird", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_fish", title: "Fish", speech: "Fish", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_horse", title: "Horse", speech: "Horse", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_cow", title: "Cow", speech: "Cow", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_pig", title: "Pig", speech: "Pig", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_chicken", title: "Chicken", speech: "Chicken", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_duck", title: "Duck", speech: "Duck", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_sheep", title: "Sheep", speech: "Sheep", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_rabbit", title: "Rabbit", speech: "Rabbit", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_mouse", title: "Mouse", speech: "Mouse", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_frog", title: "Frog", speech: "Frog", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_butterfly", title: "Butterfly", speech: "Butterfly", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_snake", title: "Snake", speech: "Snake", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_turtle", title: "Turtle", speech: "Turtle", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_lion", title: "Lion", speech: "Lion", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_elephant", title: "Elephant", speech: "Elephant", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_giraffe", title: "Giraffe", speech: "Giraffe", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_monkey", title: "Monkey", speech: "Monkey", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_penguin", title: "Penguin", speech: "Penguin", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_bear", title: "Bear", speech: "Bear", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_zebra", title: "Zebra", speech: "Zebra", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_owl", title: "Owl", speech: "Owl", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_bee", title: "Bee", speech: "Bee", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_ant", title: "Ant", speech: "Ant", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_spider", title: "Spider", speech: "Spider", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_dolphin", title: "Dolphin", speech: "Dolphin", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_shark", title: "Shark", speech: "Shark", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_whale", title: "Whale", speech: "Whale", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_crab", title: "Crab", speech: "Crab", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_octopus", title: "Octopus", speech: "Octopus", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_parrot", title: "Parrot", speech: "Parrot", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_eagle", title: "Eagle", speech: "Eagle", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_flamingo", title: "Flamingo", speech: "Flamingo", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_fox", title: "Fox", speech: "Fox", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_deer", title: "Deer", speech: "Deer", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_wolf", title: "Wolf", speech: "Wolf", imageURL: nil, colorHex: 0xFFB347),
            CommunicationCard(id: "animal_crocodile", title: "Crocodile", speech: "Crocodile", imageURL: nil, colorHex: 0xFFB347),
        ]
    ),
    CardCollection(
        id: "__default_colors",
        title: "Colors",
        colorHex: 0xFF6B6B,
        order: 1,
        mediaCategories: ["colors"],
        cards: [
            CommunicationCard(id: "color_red", title: "Red", speech: "Red", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_orange", title: "Orange", speech: "Orange", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_yellow", title: "Yellow", speech: "Yellow", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_green", title: "Green", speech: "Green", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_blue", title: "Blue", speech: "Blue", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_purple", title: "Purple", speech: "Purple", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_pink", title: "Pink", speech: "Pink", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_brown", title: "Brown", speech: "Brown", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_black", title: "Black", speech: "Black", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_white", title: "White", speech: "White", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_gray", title: "Gray", speech: "Gray", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_gold", title: "Gold", speech: "Gold", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_silver", title: "Silver", speech: "Silver", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_beige", title: "Beige", speech: "Beige", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_maroon", title: "Maroon", speech: "Maroon", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_navy", title: "Navy", speech: "Navy", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_teal", title: "Teal", speech: "Teal", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_coral", title: "Coral", speech: "Coral", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_lime", title: "Lime", speech: "Lime", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_lavender", title: "Lavender", speech: "Lavender", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_cyan", title: "Cyan", speech: "Cyan", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_magenta", title: "Magenta", speech: "Magenta", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_olive", title: "Olive", speech: "Olive", imageURL: nil, colorHex: 0xFF6B6B),
            CommunicationCard(id: "color_peach", title: "Peach", speech: "Peach", imageURL: nil, colorHex: 0xFF6B6B),
        ]
    ),
    CardCollection(
        id: "__default_food",
        title: "Food & Drinks",
        colorHex: 0x4ECDC4,
        order: 2,
        mediaCategories: ["food", "food-drinks"],
        cards: [
            CommunicationCard(id: "food_apple", title: "Apple", speech: "Apple", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_banana", title: "Banana", speech: "Banana", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_bread", title: "Bread", speech: "Bread", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_milk", title: "Milk", speech: "Milk", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_water", title: "Water", speech: "Water", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_juice", title: "Juice", speech: "Juice", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_cheese", title: "Cheese", speech: "Cheese", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_rice", title: "Rice", speech: "Rice", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_pizza", title: "Pizza", speech: "Pizza", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_cake", title: "Cake", speech: "Cake", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_egg", title: "Egg", speech: "Egg", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_grape", title: "Grape", speech: "Grape", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_strawberry", title: "Strawberry", speech: "Strawberry", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_carrot", title: "Carrot", speech: "Carrot", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_tomato", title: "Tomato", speech: "Tomato", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_potato", title: "Potato", speech: "Potato", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_corn", title: "Corn", speech: "Corn", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_onion", title: "Onion", speech: "Onion", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_mushroom", title: "Mushroom", speech: "Mushroom", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_broccoli", title: "Broccoli", speech: "Broccoli", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_soup", title: "Soup", speech: "Soup", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_pasta", title: "Pasta", speech: "Pasta", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_burger", title: "Burger", speech: "Burger", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_hotdog", title: "Hot Dog", speech: "Hot Dog", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_icecream", title: "Ice Cream", speech: "Ice Cream", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_cookie", title: "Cookie", speech: "Cookie", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_chocolate", title: "Chocolate", speech: "Chocolate", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_donut", title: "Donut", speech: "Donut", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_pancake", title: "Pancake", speech: "Pancake", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_cereal", title: "Cereal", speech: "Cereal", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_popcorn", title: "Popcorn", speech: "Popcorn", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_watermelon", title: "Watermelon", speech: "Watermelon", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_lemon", title: "Lemon", speech: "Lemon", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_pineapple", title: "Pineapple", speech: "Pineapple", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_mango", title: "Mango", speech: "Mango", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_cherry", title: "Cherry", speech: "Cherry", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_pear", title: "Pear", speech: "Pear", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_orange_fruit", title: "Orange", speech: "Orange", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_grapefruit", title: "Grapefruit", speech: "Grapefruit", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_kiwi", title: "Kiwi", speech: "Kiwi", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_peach_fruit", title: "Peach", speech: "Peach", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_plum", title: "Plum", speech: "Plum", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_cucumber", title: "Cucumber", speech: "Cucumber", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_pepper", title: "Pepper", speech: "Pepper", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_avocado", title: "Avocado", speech: "Avocado", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_sandwich", title: "Sandwich", speech: "Sandwich", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_taco", title: "Taco", speech: "Taco", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_sushi", title: "Sushi", speech: "Sushi", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_noodles", title: "Noodles", speech: "Noodles", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_sausage", title: "Sausage", speech: "Sausage", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_tea", title: "Tea", speech: "Tea", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_coffee", title: "Coffee", speech: "Coffee", imageURL: nil, colorHex: 0x4ECDC4),
            CommunicationCard(id: "food_smoothie", title: "Smoothie", speech: "Smoothie", imageURL: nil, colorHex: 0x4ECDC4),
        ]
    ),
    CardCollection(
        id: "__default_body",
        title: "Body Parts",
        colorHex: 0xA8E6CF,
        order: 3,
        mediaCategories: ["body", "body-parts"],
        cards: [
            CommunicationCard(id: "body_head", title: "Head", speech: "Head", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_hair", title: "Hair", speech: "Hair", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_face", title: "Face", speech: "Face", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_eyes", title: "Eyes", speech: "Eyes", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_nose", title: "Nose", speech: "Nose", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_mouth", title: "Mouth", speech: "Mouth", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_ears", title: "Ears", speech: "Ears", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_teeth", title: "Teeth", speech: "Teeth", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_tongue", title: "Tongue", speech: "Tongue", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_chin", title: "Chin", speech: "Chin", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_neck", title: "Neck", speech: "Neck", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_shoulders", title: "Shoulders", speech: "Shoulders", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_chest", title: "Chest", speech: "Chest", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_back", title: "Back", speech: "Back", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_stomach", title: "Stomach", speech: "Stomach", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_hands", title: "Hands", speech: "Hands", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_fingers", title: "Fingers", speech: "Fingers", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_thumb", title: "Thumb", speech: "Thumb", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_wrist", title: "Wrist", speech: "Wrist", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_arms", title: "Arms", speech: "Arms", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_elbow", title: "Elbow", speech: "Elbow", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_legs", title: "Legs", speech: "Legs", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_knees", title: "Knees", speech: "Knees", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_feet", title: "Feet", speech: "Feet", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_toes", title: "Toes", speech: "Toes", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_ankle", title: "Ankle", speech: "Ankle", imageURL: nil, colorHex: 0xA8E6CF),
            CommunicationCard(id: "body_heel", title: "Heel", speech: "Heel", imageURL: nil, colorHex: 0xA8E6CF),
        ]
    ),
    CardCollection(
        id: "__default_shapes",
        title: "Shapes",
        colorHex: 0xDDA0DD,
        order: 4,
        mediaCategories: ["shapes"],
        cards: [
            CommunicationCard(id: "shape_circle", title: "Circle", speech: "Circle", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_square", title: "Square", speech: "Square", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_triangle", title: "Triangle", speech: "Triangle", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_rectangle", title: "Rectangle", speech: "Rectangle", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_oval", title: "Oval", speech: "Oval", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_star", title: "Star", speech: "Star", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_heart", title: "Heart", speech: "Heart", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_diamond", title: "Diamond", speech: "Diamond", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_hexagon", title: "Hexagon", speech: "Hexagon", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_pentagon", title: "Pentagon", speech: "Pentagon", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_crescent", title: "Crescent", speech: "Crescent", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_cross", title: "Cross", speech: "Cross", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_arrow", title: "Arrow", speech: "Arrow", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_sphere", title: "Sphere", speech: "Sphere", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_cube", title: "Cube", speech: "Cube", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_pyramid", title: "Pyramid", speech: "Pyramid", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_cylinder", title: "Cylinder", speech: "Cylinder", imageURL: nil, colorHex: 0xDDA0DD),
            CommunicationCard(id: "shape_cone", title: "Cone", speech: "Cone", imageURL: nil, colorHex: 0xDDA0DD),
        ]
    ),
    CardCollection(
        id: "__default_emotions",
        title: "Emotions",
        colorHex: 0xFFD93D,
        order: 5,
        mediaCategories: ["emotions", "feelings"],
        cards: [
            CommunicationCard(id: "emotion_happy", title: "Happy", speech: "Happy", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_sad", title: "Sad", speech: "Sad", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_angry", title: "Angry", speech: "Angry", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_scared", title: "Scared", speech: "Scared", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_surprised", title: "Surprised", speech: "Surprised", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_tired", title: "Tired", speech: "Tired", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_excited", title: "Excited", speech: "Excited", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_calm", title: "Calm", speech: "Calm", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_confused", title: "Confused", speech: "Confused", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_shy", title: "Shy", speech: "Shy", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_proud", title: "Proud", speech: "Proud", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_grumpy", title: "Grumpy", speech: "Grumpy", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_brave", title: "Brave", speech: "Brave", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_curious", title: "Curious", speech: "Curious", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_lonely", title: "Lonely", speech: "Lonely", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_grateful", title: "Grateful", speech: "Grateful", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_nervous", title: "Nervous", speech: "Nervous", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_silly", title: "Silly", speech: "Silly", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_love", title: "Love", speech: "Love", imageURL: nil, colorHex: 0xFFD93D),
            CommunicationCard(id: "emotion_bored", title: "Bored", speech: "Bored", imageURL: nil, colorHex: 0xFFD93D),
        ]
    ),
    CardCollection(
        id: "__default_transport",
        title: "Transport",
        colorHex: 0x82B1FF,
        order: 6,
        mediaCategories: ["transport", "vehicles"],
        cards: [
            CommunicationCard(id: "transport_car", title: "Car", speech: "Car", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_bus", title: "Bus", speech: "Bus", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_train", title: "Train", speech: "Train", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_truck", title: "Truck", speech: "Truck", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_airplane", title: "Airplane", speech: "Airplane", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_helicopter", title: "Helicopter", speech: "Helicopter", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_boat", title: "Boat", speech: "Boat", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_ship", title: "Ship", speech: "Ship", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_bicycle", title: "Bicycle", speech: "Bicycle", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_motorcycle", title: "Motorcycle", speech: "Motorcycle", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_scooter", title: "Scooter", speech: "Scooter", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_taxi", title: "Taxi", speech: "Taxi", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_ambulance", title: "Ambulance", speech: "Ambulance", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_firetruck", title: "Fire Truck", speech: "Fire Truck", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_policecar", title: "Police Car", speech: "Police Car", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_tractor", title: "Tractor", speech: "Tractor", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_rocket", title: "Rocket", speech: "Rocket", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_submarine", title: "Submarine", speech: "Submarine", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_balloon", title: "Hot Air Balloon", speech: "Hot Air Balloon", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_skateboard", title: "Skateboard", speech: "Skateboard", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_roller_coaster", title: "Roller Coaster", speech: "Roller Coaster", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_jeep", title: "Jeep", speech: "Jeep", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_van", title: "Van", speech: "Van", imageURL: nil, colorHex: 0x82B1FF),
            CommunicationCard(id: "transport_canoe", title: "Canoe", speech: "Canoe", imageURL: nil, colorHex: 0x82B1FF),
        ]
    ),
    CardCollection(
        id: "__default_numbers",
        title: "Numbers",
        colorHex: 0x87CEEB,
        order: 7,
        mediaCategories: ["numbers"],
        cards: [
            CommunicationCard(id: "num_1", title: "One", speech: "One", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_2", title: "Two", speech: "Two", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_3", title: "Three", speech: "Three", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_4", title: "Four", speech: "Four", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_5", title: "Five", speech: "Five", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_6", title: "Six", speech: "Six", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_7", title: "Seven", speech: "Seven", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_8", title: "Eight", speech: "Eight", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_9", title: "Nine", speech: "Nine", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_10", title: "Ten", speech: "Ten", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_11", title: "Eleven", speech: "Eleven", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_12", title: "Twelve", speech: "Twelve", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_13", title: "Thirteen", speech: "Thirteen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_14", title: "Fourteen", speech: "Fourteen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_15", title: "Fifteen", speech: "Fifteen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_16", title: "Sixteen", speech: "Sixteen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_17", title: "Seventeen", speech: "Seventeen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_18", title: "Eighteen", speech: "Eighteen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_19", title: "Nineteen", speech: "Nineteen", imageURL: nil, colorHex: 0x87CEEB),
            CommunicationCard(id: "num_20", title: "Twenty", speech: "Twenty", imageURL: nil, colorHex: 0x87CEEB),
        ]
    ),
    CardCollection(
        id: "__default_letters",
        title: "Letters",
        colorHex: 0x98D8C8,
        order: 8,
        mediaCategories: ["letters", "alphabet"],
        cards: [
            CommunicationCard(id: "letter_a", title: "A", speech: "A", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_b", title: "B", speech: "B", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_c", title: "C", speech: "C", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_d", title: "D", speech: "D", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_e", title: "E", speech: "E", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_f", title: "F", speech: "F", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_g", title: "G", speech: "G", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_h", title: "H", speech: "H", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_i", title: "I", speech: "I", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_j", title: "J", speech: "J", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_k", title: "K", speech: "K", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_l", title: "L", speech: "L", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_m", title: "M", speech: "M", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_n", title: "N", speech: "N", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_o", title: "O", speech: "O", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_p", title: "P", speech: "P", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_q", title: "Q", speech: "Q", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_r", title: "R", speech: "R", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_s", title: "S", speech: "S", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_t", title: "T", speech: "T", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_u", title: "U", speech: "U", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_v", title: "V", speech: "V", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_w", title: "W", speech: "W", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_x", title: "X", speech: "X", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_y", title: "Y", speech: "Y", imageURL: nil, colorHex: 0x98D8C8),
            CommunicationCard(id: "letter_z", title: "Z", speech: "Z", imageURL: nil, colorHex: 0x98D8C8),
        ]
    ),
]
