#!/usr/bin/env node
/**
 * Generate the locale registry for both platforms from `tools/locales.mjs`.
 *
 * Writes:
 * - `packages/i18n/src/locales.generated.ts` — the web registry
 * - `packages/tikokit-ios/Sources/TikoKit/TikoLocales.generated.swift` — the iOS one
 *
 * The list used to live in three places and had drifted; neither generated file
 * should be edited by hand.
 *
 * Usage:
 *   node tools/generate-locales.mjs           # write
 *   node tools/generate-locales.mjs --check   # fail if stale (for CI)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { locales, fallbackLocale } from './locales.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')

const HEADER = [
  '// Generated by tools/generate-locales.mjs — do not edit.',
  '// The languages Tiko offers live in tools/locales.mjs, which writes this file',
  '// and its Swift counterpart so the two platforms cannot drift.',
  '',
].join('\n')

function swiftString(value) {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function web() {
  const lines = [HEADER]
  lines.push("import type { TikoLocale, TikoLocaleEntry } from './locales'")
  lines.push('')
  lines.push('/** Every locale the app offers, in picker order. */')
  lines.push('export const tikoLocaleEntries: readonly TikoLocaleEntry[] = [')
  for (const locale of locales) {
    const parts = [
      `code: '${locale.code}'`,
      `name: ${JSON.stringify(locale.name)}`,
      `native: ${JSON.stringify(locale.native)}`,
    ]
    if (locale.rtl) parts.push('rtl: true')
    parts.push(`talk: ${locale.talk === true}`)
    parts.push(`ui: '${locale.ui}'`)
    lines.push(`  { ${parts.join(', ')} },`)
  }
  lines.push('] as const')
  lines.push('')
  lines.push('/** The locale a missing translation falls back to. */')
  lines.push(`export const fallbackLocale = '${fallbackLocale}' as const`)
  lines.push('')
  lines.push('/** Locale codes, in picker order. */')
  lines.push('export const tikoLocaleCodes = tikoLocaleEntries.map((entry) => entry.code) as readonly TikoLocale[]')
  lines.push('')
  return lines.join('\n')
}

function ios() {
  const lines = [HEADER]
  lines.push('import Foundation')
  lines.push('')
  lines.push('public extension TikoLanguage {')
  lines.push('    /// Every language the app offers, in picker order.')
  lines.push('    static let allLanguages: [TikoLanguage] = [')
  for (const locale of locales) {
    lines.push(
      `        TikoLanguage(id: ${swiftString(locale.code)}, `
      + `title: ${swiftString(locale.name)}, `
      + `nativeTitle: ${swiftString(locale.native)}, `
      + `isRightToLeft: ${locale.rtl === true}, `
      + `hasTalkGrammar: ${locale.talk === true}, `
      + `interfaceCoverage: .${locale.ui}),`,
    )
  }
  lines.push('    ]')
  lines.push('')
  lines.push('    /// The codes `TikoDeviceDefaults` matches the device language against.')
  lines.push('    static var allLanguageCodes: [String] { allLanguages.map(\\.id) }')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

const outputs = [
  ['packages/i18n/src/locales.generated.ts', web()],
  ['packages/tikokit-ios/Sources/TikoKit/TikoLocales.generated.swift', ios()],
]

let stale = false
for (const [path, contents] of outputs) {
  const full = join(ROOT, path)
  const previous = existsSync(full) ? readFileSync(full, 'utf8') : null
  if (previous === contents) {
    console.log(`OK   ${path} is up to date`)
    continue
  }
  if (CHECK) {
    console.error(`STALE ${path}`)
    stale = true
    continue
  }
  writeFileSync(full, contents)
  console.log(`Wrote ${path}`)
}

console.log(`${locales.length} locales; ${locales.filter((l) => l.talk).length} with Talk grammar.`)
if (stale) process.exit(1)
