// Generated by tools/generate-locales.mjs — do not edit.
// The languages Tiko offers live in tools/locales.mjs, which writes this file
// and its Swift counterpart so the two platforms cannot drift.

import type { TikoLocale, TikoLocaleEntry } from './locales'

/** Every locale the app offers, in picker order. */
export const tikoLocaleEntries: readonly TikoLocaleEntry[] = [
  { code: 'en', name: "English", native: "English", talk: true, ui: 'full' },
  { code: 'nl', name: "Dutch", native: "Nederlands", talk: true, ui: 'full' },
  { code: 'de', name: "German", native: "Deutsch", talk: true, ui: 'full' },
  { code: 'fr', name: "French", native: "Français", talk: true, ui: 'full' },
  { code: 'es', name: "Spanish", native: "Español", talk: true, ui: 'full' },
  { code: 'pt', name: "Portuguese", native: "Português", talk: true, ui: 'full' },
  { code: 'it', name: "Italian", native: "Italiano", talk: true, ui: 'full' },
  { code: 'mt', name: "Maltese", native: "Malti", talk: true, ui: 'full' },
  { code: 'ja', name: "Japanese", native: "日本語", talk: true, ui: 'core' },
  { code: 'zh', name: "Chinese", native: "中文", talk: true, ui: 'core' },
  { code: 'ko', name: "Korean", native: "한국어", talk: true, ui: 'core' },
  { code: 'ar', name: "Arabic", native: "العربية", rtl: true, talk: true, ui: 'core' },
  { code: 'hy', name: "Armenian", native: "Հայերեն", talk: true, ui: 'core' },
  { code: 'id', name: "Indonesian", native: "Bahasa Indonesia", talk: true, ui: 'core' },
  { code: 'ms', name: "Malay", native: "Bahasa Melayu", talk: true, ui: 'core' },
  { code: 'vi', name: "Vietnamese", native: "Tiếng Việt", talk: true, ui: 'core' },
  { code: 'af', name: "Afrikaans", native: "Afrikaans", talk: true, ui: 'core' },
  { code: 'sv', name: "Swedish", native: "Svenska", talk: true, ui: 'core' },
  { code: 'da', name: "Danish", native: "Dansk", talk: true, ui: 'core' },
  { code: 'nb', name: "Norwegian", native: "Norsk", talk: true, ui: 'core' },
  { code: 'is', name: "Icelandic", native: "Íslenska", talk: true, ui: 'core' },
  { code: 'fy', name: "West Frisian", native: "Frysk", talk: true, ui: 'core' },
  { code: 'lb', name: "Luxembourgish", native: "Lëtzebuergesch", talk: true, ui: 'core' },
  { code: 'ca', name: "Catalan", native: "Català", talk: true, ui: 'core' },
  { code: 'gl', name: "Galician", native: "Galego", talk: true, ui: 'core' },
  { code: 'ro', name: "Romanian", native: "Română", talk: true, ui: 'core' },
  { code: 'pap', name: "Papiamentu", native: "Papiamentu", talk: true, ui: 'core' },
  { code: 'ru', name: "Russian", native: "Русский", talk: true, ui: 'core' },
  { code: 'uk', name: "Ukrainian", native: "Українська", talk: true, ui: 'core' },
  { code: 'be', name: "Belarusian", native: "Беларуская", talk: true, ui: 'core' },
  { code: 'pl', name: "Polish", native: "Polski", talk: true, ui: 'core' },
  { code: 'cs', name: "Czech", native: "Čeština", talk: true, ui: 'core' },
  { code: 'sk', name: "Slovak", native: "Slovenčina", talk: true, ui: 'core' },
  { code: 'sl', name: "Slovenian", native: "Slovenščina", talk: true, ui: 'core' },
  { code: 'hr', name: "Croatian", native: "Hrvatski", talk: true, ui: 'core' },
  { code: 'sr', name: "Serbian", native: "Српски", talk: true, ui: 'core' },
  { code: 'bs', name: "Bosnian", native: "Bosanski", talk: true, ui: 'core' },
  { code: 'cnr', name: "Montenegrin", native: "Crnogorski", talk: true, ui: 'core' },
  { code: 'bg', name: "Bulgarian", native: "Български", talk: true, ui: 'core' },
  { code: 'mk', name: "Macedonian", native: "Македонски", talk: true, ui: 'core' },
  { code: 'lt', name: "Lithuanian", native: "Lietuvių", talk: true, ui: 'core' },
  { code: 'lv', name: "Latvian", native: "Latviešu", talk: true, ui: 'core' },
  { code: 'fi', name: "Finnish", native: "Suomi", talk: true, ui: 'core' },
  { code: 'et', name: "Estonian", native: "Eesti", talk: true, ui: 'core' },
  { code: 'hu', name: "Hungarian", native: "Magyar", talk: true, ui: 'core' },
  { code: 'cy', name: "Welsh", native: "Cymraeg", talk: true, ui: 'core' },
  { code: 'ga', name: "Irish", native: "Gaeilge", talk: true, ui: 'core' },
  { code: 'bn', name: "Bengali", native: "বাংলা", talk: true, ui: 'core' },
  { code: 'hi', name: "Hindi", native: "हिन्दी", talk: true, ui: 'core' },
  { code: 'el', name: "Greek", native: "Ελληνικά", talk: true, ui: 'core' },
  { code: 'sq', name: "Albanian", native: "Shqip", talk: true, ui: 'core' },
  { code: 'tr', name: "Turkish", native: "Türkçe", talk: true, ui: 'core' },
  { code: 'eu', name: "Basque", native: "Euskara", talk: true, ui: 'core' },
  { code: 'ka', name: "Georgian", native: "ქართული", talk: true, ui: 'core' },
] as const

/** The locale a missing translation falls back to. */
export const fallbackLocale = 'en' as const

/** Locale codes, in picker order. */
export const tikoLocaleCodes = tikoLocaleEntries.map((entry) => entry.code) as readonly TikoLocale[]
